name: "Version Calculation"
description: "Calculate the next version based on the latest Git tag."
author: "Deepworks"
inputs:
  default_version:
    description: "Default version to use when no tags exist"
    required: false
    default: "v0.1.0"
outputs:
  next_version:
    description: "The calculated next version."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "tag"
  color: "blue"