name: "Manage Release"
description: "Manages GitHub draft releases - create, get, and update operations"
author: "Deepworks"

inputs:
  github_token:        # Changed from github-token to github_token
    description: 'GitHub token for API access'
    required: true
  operation:
    description: 'Operation to perform (draft, get, update)'
    required: false
    default: 'get'
  name:
    description: 'Release name for draft operation'
    required: false
    default: 'Draft Release'
  body:
    description: 'Initial release body for draft operation'
    required: false
    default: ''
  content:
    description: 'Content for update operation'
    required: false
  update_mode:
    description: 'How to update content (replace, append, prepend)'
    required: false
    default: 'replace'

outputs:
  id:
    description: 'Release ID'
  body:
    description: 'Release content'
  tag_name:
    description: 'Release tag name'
  name:
    description: 'Release name'
  exists:
    description: 'Whether draft release exists (true/false)'

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "edit"
  color: "blue"