name: Version Calculation

on:
  workflow_dispatch:  # allows manual triggering
  workflow_call:
    secrets:
        token:
          description: 'GitHub Repository Token'
          required: false
jobs:
  calculate-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: fetch all history and tags
      
      - name: Calculate next version
        id: version
        uses: deepworks-net/github.toolkit/actions/version_calculation@main  # Path to your local action
      
      # Optional: You can use the calculated version in subsequent steps
      - name: Display calculated version
        run: echo "Next version will be ${{ steps.version.outputs.next_version }}"