name: "Changelog"
description: "Manages CHANGELOG.md file content and formatting"
inputs:
  content:
    description: 'Content to add to changelog'
    required: true
  mode:
    description: 'Operation mode (unreleased, release)'
    required: true
  version:
    description: 'Version number'
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    CONTENT: ${{ inputs.content }}
    MODE: ${{ inputs.mode }}
    VERSION: ${{ inputs.version }}