name: Create Release Tag

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-tag:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Create and Push Tag
        run: |
          # Extract version from branch name
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}
          
          echo "Creating tag $VERSION from release branch $BRANCH_NAME"
          
          git tag $VERSION
          git push origin $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}