name: MkDocs gh-pages Publish

on:
  # Keep existing trigger for this repo
  push:
    branches: 
      - main
  # Add workflow_call to make it reusable
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        default: '3.x'
        required: false
        type: string
      requirements-file:
        description: 'Path to requirements.txt'
        default: 'requirements.txt'
        required: false
        type: string
      readme-source:
        description: 'Source path for README.md'
        default: 'README.md'
        required: false
        type: string
      readme-destination:
        description: 'Destination path for README.md'
        default: 'docs/README.md'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version || '3.x' }}
      
      - run: pip install -r ${{ inputs.requirements-file || 'requirements.txt' }}
      
      - run: cp ${{ inputs.readme-source || 'README.md' }} ${{ inputs.readme-destination || 'docs/README.md' }}
      
      - run: mkdocs gh-deploy --force