name: MkDocs gh-pages Publish

on:
  # Keep existing trigger for this repo
  push:
    branches: 
      - main
  # Add workflow_call to make it reusable
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        default: '3.x'
        required: false
        type: string
      requirements-file:
        description: 'Path to requirements.txt'
        default: 'requirements.txt'
        required: false
        type: string
      readme-source:
        description: 'Source path for README'
        default: 'README'
        required: false
        type: string
      readme-destination:
        description: 'Destination path for README'
        default: 'docs/repo/inc/README.md'
        required: false
        type: string
      changelog-source:
        description: 'Source path for CHANGELOG'
        default: 'CHANGELOG'
        required: false
        type: string
      changelog-destination:
        description: 'Destination path for CHANGELOG'
        default: 'docs/repo/inc/CHANGELOG.md'
        required: false
        type: string
      license-source:
        description: 'Source path for LICENSE'
        default: 'LICENSE'
        required: false
        type: string
      license-destination:
        description: 'Destination path for LICENSE'
        default: 'docs/repo/inc/LICENSE.md'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version || '3.x' }}
      - run: pip install -r ${{ inputs.requirements-file || 'requirements.txt' }}
      - run: cp ${{ inputs.readme-source || 'README' }} ${{ inputs.readme-destination || 'docs/repo/inc/README.md' }}
      - run: cp ${{ inputs.changelog-source || 'CHANGELOG' }} ${{ inputs.changelog-destination || 'docs/repo/inc/CHANGELOG.md' }}
      - run: cp ${{ inputs.license-source || 'LICENSE' }} ${{ inputs.license-destination || 'docs/repo/inc/LICENSE.md' }}
      - run: mkdocs gh-deploy --force