name: Prepare Release Branch

on:
  push:
    tags:
      - 'prep'  # Simple trigger

jobs:
  create-release-branch:
    if: github.ref_type == 'tag' && github.ref == 'refs/tags/prep'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}  # Ensures the current repository
          ref: staging  # Explicitly specify the staging branch
          fetch-depth: 0
          
      - name: Calculate Version
        uses: ./actions/version_calculator
        id: version

      - name: Update Version Numbers
        uses: ./actions/version_updater
        with:
          version: ${{ steps.version.outputs.next_version }}
          files: 'mkdocs.yml'

      - name: Get Release Content
        uses: ./actions/release_notes
        id: notes
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          mode: 'prepare-release'
          version: ${{ steps.version.outputs.next_version }}

      - name: Update Changelog File
        uses: ./actions/update_changelog
        with:
          content: ${{ steps.notes.outputs.content }}
          mode: 'release'
          version: ${{ steps.version.outputs.next_version }}

      - name: Create Release Branch & PR
        uses: ./actions/git_ops
        with:
          files: 'CHANGELOG.md'
          commit-message: 'Prepare release ${{ steps.version.outputs.next_version }}'
          create-pr: true
          pr-title: 'Release ${{ steps.version.outputs.next_version }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
