name: Publish Github Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          publish: true  # Always publish since we're only triggering on tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}