name: Release Drafter

on:
  push:
    branches:
      - develop
  workflow_call:
    inputs:
      tag-name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: false
        type: string
      draft:
        description: 'Create as draft release'
        required: false
        type: boolean
        default: false
    secrets:
      token:
        description: 'GitHub token for release creation'
        required: false

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}  # Ensures the current repository
          ref: develop  # Explicitly specify the develop branch
          fetch-depth: 0

      - name: Debug Repository Structure
        run: |
          echo "Current directory:"
          pwd
          echo "Files in repository:"
          ls -R /home/runner/work/github.actions/github.actions

      - name: Debug Action Files
        run: |
          echo "Contents of actions/version_calculation:"
          ls -l /home/runner/work/github.actions/github.actions/actions/version_calculation
          echo "Contents of action.yml:"
          cat /home/runner/work/github.actions/github.actions/actions/version_calculation/action.yml

      - name: Calculate Next Version
        uses: ./actions/version_calculation
        id: version
      
      - name: Set Output for Version
        run: echo "::set-output name=version::${{ steps.version.outputs.next_version }}"

      - name: Draft Release
        uses: release-drafter/release-drafter@v6
        with:
          publish: false
          version: ${{ steps.version.outputs.next_version }}
          header: |
            ## Draft Release ${{ steps.version.outputs.next_version }}
          footer: |
            See the [Changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for more details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - uses: release-drafter/release-drafter@v6
        with:
          publish: true
          tag: ${{ github.ref_name }}
          header: |
            ## Release ${{ github.ref_name }}
          footer: |
            See the [Changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for more details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
