name: Release Notes

on:
  workflow_dispatch:  # allows manual triggering

jobs:
  get-release-notes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            repository: ${{ github.repository }}  # Ensures the current repository
            ref: staging  # Explicitly specify the staging branch
            fetch-depth: 0

      - name: Get Release Content
        uses: ./actions/release_notes
        id: notes
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            mode: 'prepare-release'
            version: ${{ steps.version.outputs.next_version }}