name: Draft Github Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          publish: ${{ contains(github.ref, 'refs/tags/') }}  # Only publish when it's a tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}