name: Test Tag Detection
on:
  push:
    tags:
      - '*'  # Match any tag

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Tag
        run: |
          echo "Tag pushed: ${{ github.ref }}"