# update-changelog.yml 
name: "Update Changelog"
on:
  pull_request:
    types: [opened, reopened, synchronize]
  repository_dispatch:
    types: [update_changelog]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.client_payload.tag || 'Unreleased' }}
          release-notes: ${{ github.event.client_payload.notes || '' }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "docs: update CHANGELOG.md for ${{ github.event.client_payload.tag || 'Unreleased' }}"
          file_pattern: CHANGELOG.md