name: Update Changelog
on:
  pull_request:
    branches:
      - staging  # Updated to new naming convention
    types: [closed]

jobs:
  update_changelog:
    # Only run if the PR was merged (not just closed)
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}  # Ensures the current repository
          ref: staging    # Updated to new naming convention
          fetch-depth: 0

      - name: Calculate Next Version
        uses: ./actions/version_calculation
        id: version
          
      - name: Update Changelog
        uses: ./actions/changelog_update
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.version.outputs.next_version }}
          