# update-changelog.yml 
name: "Update Changelog"
on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  update:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
      
      - name: Ensure Unreleased Section Exists and Add PR Notes
        run: |
            # Ensure "## Unreleased" exists at the top
            if ! grep -q "## Unreleased" CHANGELOG.md; then
              echo -e "## Unreleased" > tmp_changelog
              cat CHANGELOG.md >> tmp_changelog
              mv tmp_changelog CHANGELOG.md
            fi
  
            # Append PR details directly under "## Unreleased" without extra spacing
            PR_DETAILS="- PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
            awk -v details="$PR_DETAILS" '
            /^## Unreleased$/ {print; print details; next} 1
            ' CHANGELOG.md > tmp && mv tmp CHANGELOG.md

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: develop
          commit_message: "docs: update CHANGELOG.md"
          file_pattern: CHANGELOG.md