name: Update Changelog for Release
on:
  push:
    tags:
      - '*'

jobs:
  update-changelog:
    if: github.ref_type == 'tag' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
          
      - name: Update Changelog for Release
        run: |
          echo "Processing release for tag..."
          
          # Get the tag name
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag name: $TAG_NAME"
          
          # Get today's date
          TODAY=$(date +"%m/%d/%Y")
          echo "Release date: $TODAY"
          
          # Create temp file
          TEMP_FILE=$(mktemp)
          
          # Read the current changelog and process it
          awk -v tag="$TAG_NAME" -v today="$TODAY" -v repo="${GITHUB_REPOSITORY#*/}" '
            BEGIN {
              # Initialize variables
              in_unreleased = 0
              unreleased_content = ""
              printed_new_section = 0
            }
            
            # Detect Unreleased section
            /## \*\*.*Unreleased\*\*/ {
              in_unreleased = 1
              print
              next
            }
            
            # Start of any other section ends Unreleased
            /^## \*\*/ {
              if (in_unreleased) {
                in_unreleased = 0
                # Print the new versioned section before the next section
                print ""
                print "## **[(" today ") - " tag "](https://github.com/suny-upstate-cwt/" repo "/releases/tag/" tag ")**"
                print unreleased_content
                print ""
              }
              print
              next
            }
            
            # Collect content from Unreleased section
            {
              if (in_unreleased) {
                if ($0 != "") {
                  unreleased_content = unreleased_content $0 "\n"
                }
              } else {
                print
              }
            }
            
            # At end of file, print new section if we havent yet
            END {
              if (in_unreleased && !printed_new_section) {
                print ""
                print "## **[(" today ") - " tag "](https://github.com/suny-upstate-cwt/" repo "/releases/tag/" tag ")**"
                print unreleased_content
              }
            }
          ' CHANGELOG.md > "$TEMP_FILE"
          
          # Create new Unreleased section at the top (after header)
          awk '
            NR == 1 { print; next }
            NR == 2 { 
              print
              print ""
              print "## **" strftime("%m/%d/%Y") " - Unreleased**"
              print ""
            }
            { print }
          ' "$TEMP_FILE" > CHANGELOG.md
          
          echo "Updated CHANGELOG.md content:"
          cat CHANGELOG.md
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          echo "Git status:"
          git status
          
          echo "Checking for changes in CHANGELOG.md..."
          if git status --porcelain | grep "CHANGELOG.md"; then
            echo "Changes detected, committing..."
            git add CHANGELOG.md
            git commit -m "Update CHANGELOG.md for release [skip ci]"
            git push origin develop
            echo "Changes pushed successfully"
          else
            echo "No changes detected in CHANGELOG.md"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}