# update-changelog.yml 
name: "Update Changelog"

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "✏️ Generate release changelog"
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
