name: Update Changelog
on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  update_changelog:
    # Only run if the PR was merged (not just closed)
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}  # Ensures the current repository
          ref: develop  # Explicitly specify the develop branch
          fetch-depth: 0

      - name: Calculate Next Version
        uses: ./actions/version_calculation
        id: version
          
      - name: Update Changelog
        run: |
          echo "Processing merged pull request..."
          
          TODAY=$(date +"%m/%d/%Y")
          NEW_VERSION="${{ steps.version.outputs.next_version }}"
          
          # Create temp file
          TEMP_FILE=$(mktemp)
          
          # Just transform the Unreleased header to a release header
          sed "/## \*\*.*- Unreleased\*\*/c## **[(${TODAY}) - v${NEW_VERSION}](https://github.com/deepworks-net/github.actions/releases/tag/v${NEW_VERSION})**" CHANGELOG.md > "$TEMP_FILE"
          
          cat "$TEMP_FILE" > CHANGELOG.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git status --porcelain | grep "CHANGELOG.md"; then
            git add CHANGELOG.md
            git commit -m "Update CHANGELOG.md with PR #${{ github.event.pull_request.number }} [skip ci]"
            git push origin develop
          else
            echo "No changes detected in CHANGELOG.md"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}