name: Version Calculator

on:
  workflow_dispatch:  # allows manual triggering

jobs:
  calculate-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: fetch all history and tags
      
      - name: Calculate next version
        id: version
        uses: ./actions/version_calculator@v1  # Path to your local action
      
      # Optional: You can use the calculated version in subsequent steps
      - name: Display calculated version
        run: echo "Next version will be ${{ steps.version.outputs.next_version }}"