# version-changelog.yml
name: "Version Changelog"
on:
  push:
    tags:
      - 'v*'

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

          # For PRs, generate release notes from the PR title and body
      - name: Ensure Unreleased Section Exists
        run: |
            if ! grep -q "## Unreleased" CHANGELOG.md; then
              echo -e "## Unreleased\n\n$(cat CHANGELOG.md)" > CHANGELOG.md
            fi
        
      - name: Move Unreleased to Version
        run: |
            # Read current changelog
            CHANGELOG=$(cat CHANGELOG.md)
            VERSION="${GITHUB_REF#refs/tags/}"
            DATE=$(date +%Y-%m-%d)
            
            # Replace "## Unreleased" with new version and add new unreleased section
            echo "$CHANGELOG" | sed "s/## Unreleased/## [$VERSION] - $DATE\n\n## Unreleased/" > CHANGELOG.md

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: develop
          commit_message: "docs: update CHANGELOG.md for version ${{ github.ref_name }}"
          file_pattern: CHANGELOG.md